parameters:
#    link_collate_site.example.class: LinkCollate\SiteBundle\Example

services:
#    link_collate_site.example:
#        class: %link_collate_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
