david_test_links:
    resource: "@DavidTestLinksBundle/Resources/config/routing.yml"
    prefix:   /

diarmuid_amazing:
    resource: "@DiarmuidAmazingBundle/Resources/config/routing.yml"
    prefix:   /

link_collate_site:
    resource: "@LinkCollateSiteBundle/Resources/config/routing.yml"
    prefix:   /

