Link:
    pattern:  /Link/
    defaults: { _controller: DiarmuidAmazingBundle:Default:index }

Link_add:
    pattern:  /Link/add
    defaults: { _controller: DiarmuidAmazingBundle:Default:add }

Link_update:
    pattern:  /Link/update/{id}
    defaults: { _controller: DiarmuidAmazingBundle:Default:update }

Link_delete:
    pattern: /Link/delete/{id}
    defaults: { _controller: DiarmuidAmazingBundle:Default:delete}

Link_show:
    pattern: /Link/{id}
    defaults: { _controller: DiarmuidAmazingBundle:Default:show}
