# src/Blog/BlogRegistrationBundle/Resources/config/routing.yml
account_register:
   pattern:  /register
   defaults: { _controller: BlogRegistrationBundle:User:register }

account_create:
   pattern:  /register/create
   defaults: { _controller: BlogRegistrationBundle:User:create }

account_get:
  pattern:  /get
  defaults: { _controller: BlogRegistrationBundle:User:get }