parameters:
#    blog_registration.example.class: Blog\RegistrationBundle\Example

services:
#    blog_registration.example:
#        class: %blog_registration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
