LinkCollate\SiteBundle\Entity\link:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        url:
            type: text
        description:
            type: text
        title:
            type: text
        favicon:
            type: blob
        added:
            type: datetime
        viewed:
            type: boolean
            default: false
        archived:
            type: boolean
            default: false
        deleted:
            type: boolean
            default: false
    manyToMany:
        tags:
            targetEntity: tag
            inversedBy: links
            joinTable:
                name: links_tags
                joinColumns:
                    link_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
        user:
            targetEntity: user
            inversedBy: links
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }