LinkCollate\SiteBundle\Entity\role:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        role:
            type: string
            length: 255
    oneToMany:
        users:
            targetEntity: user
            mappedBy: role