LinkCollate\SiteBundle\Entity\user:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: 255
        email:
            type: string
            length: 255
        username:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        password:
            type: string
            length: 255
        created:
            type: datetime
        enabled:
            type: boolean
            default: false
    oneToMany:
        links:
            targetEntity: link
            mappedBy: user
    oneToMany:
        tags:
            targetEntity: tag
            mappedBy: user
    manyToOne:
        role:
            targetEntity: role
            inversedBy: users
            joinColumn:
                name: role_id
                referencedColumnName: id